imports:
    - { resource: parameters.yml }
    - { resource: ns_admin.bundles.yml }
    - { resource: @NSCoreBundle/Resources/config/core-config.yml }

# Framework
framework:
    templating:
        assets_version: 1

# Avalanche Imagine
avalanche_imagine:
    source_root:  %kernel.root_dir%/../web
    web_root:     %kernel.root_dir%/../web
    cache_prefix: upload/cache
    filters:
        ns_admin_image:
            type:    thumbnail
            options: { size: [200, 200], mode: inset }
        ns_admin_preview:
            type:    thumbnail
            options: { size: [128, 128], mode: outbound }
