imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  %locale%
    trust_proxy_headers: false # Whether or not the Request object should trust proxy headers (X_FORWARDED_FOR/HTTP_CLIENT_IP)
    session:         ~
    translator:      ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    form:
        resources:
            - 'NSAdminBundle:Form:fields.html.twig'

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: true
    bundles:        [ NSAdminBundle, MopaBootstrapBundle, APFrontBundle ]
    read_from:      "%kernel.root_dir%/../public_html"
    write_to:       "%kernel.root_dir%/../public_html"
    filters:
        cssrewrite: ~

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        options:
            1002: "SET NAMES UTF8"

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        entity_managers:
            default:
                auto_mapping: true
                mappings:
                    gedmo_tree:
                        type: annotation
                        prefix: Gedmo\Tree\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Entity"
                        alias: GedmoTree
                        is_bundle: false

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

# FOS User
fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: NS\UserBundle\Entity\User

# Stof Doctrine Extensions
stof_doctrine_extensions:
    default_locale: ru
    orm:
        default:
            tree: true
            sortable: true

# Avalanche Imagine
avalanche_imagine:
    source_root:  %kernel.root_dir%/../public_html
    web_root:     %kernel.root_dir%/../public_html
    filters:
        ns_admin_image:
            type:    thumbnail
            options: { size: [200, 200], mode: inset }

        items_main_page:
            type:    thumbnail
            options: { size: [169, 120], mode: outbound }
        catalogue_item_view:
            type:    thumbnail
            options: { size: [578, 380], mode: outbound }
        catalogue_item_photo_thumb:
            type:    thumbnail
            options: { size: [80, 55], mode: outbound }
        catalogue_item_photo_thumb2:
            type:    thumbnail
            options: { size: [160, 110], mode: outbound }
        catalogue_item_photo_full:
            type:    thumbnail
            options: { size: [1000, 1000], mode: inset }
        factory_logo_32x32:
            type:    thumbnail
            options: { size: [32, 32], mode: outbound }
        factory_label_290x32:
            type:    thumbnail
            options: { size: [290, 32], mode: outbound }
        slide_front:
            type:    thumbnail
            options: { size: [194, 500], mode: outbound}

# KNP Paginator
knp_paginator:
    page_range: 5                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements

# NS Admin
ns_admin:
    bundles: [NSUserBundle, NSPagesBundle, NSNewsBundle, APCatalogueBundle, APOrdersBundle, APSlideBundle, APFileBundle, NSPropertiesBundle]

# NS Properties
ns_properties:
    properties:
        default_title:
            title: Заголовок страниц по умолчанию
        meta_keywords:
            title: Ключевые слова сайта
        meta_description:
            title: Описание сайта
        counters:
            title: Счетчики посещаемости
        email_feedback:
            title: Email для формы обратной связи
