templates:
    -
        path:    "::page-default.phtml.twig"
        title:   "Default page template"
        default: true
        areas:
            -
                name: top
                title: "Верхняя панель"
                fixed: true
            -
                name: content
                title: "Контентная область"

    -
        path:    "::page-left-menu.phtml.twig"
        title:   "Left menu page template"
        areas:
            -
                name: top
                title: "Верхняя панель"
                fixed: true
            -
                name: left
                title: "Левая панель"
                fixed: true
            -
                name: content
                title: "Контентная область"
