ns_pages:
    resource: "@NSPagesBundle/Resources/config/routing.yml"
    prefix:   /

ns_admin:
    resource: "@NSAdminBundle/Resources/config/routing.yml"
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix:   /admin

_imagine:
    resource: .
    type:     imagine
